print("Mad Libs o Escoge la Palabra")
print("----------------------------")
print("")

time_a = input("Solo se permiten números. Introduce un horario: ")
body_part = input("Una parte del cuerpo: ")
food = input("Un alimento: ")
educative_centre = input("Escriba una de las opciones (escuela o universidad): ")
lesson_01 = input("Una materia educativa: ")
lesson_02 = input("Otra materia educativa: ")
hobby = input("Un hobby o actividad: ")
time_b = input("Solo se permiten números. Introduce un horario: ")
mourning_task = input("Algo que haces todas las mañanas: ")
electric_device = input("Escribir una de las opciones (celular, tablet o notebook): ")
adjetive = input("Un adjetvio en plural: ")
home_task = input("Algo que haces en casa (verbo en tiempo presente): ")
outside_task = input("Algo que haces fuera de casa: ")
name = input("Un nombre: ")
month = input("Un mes del año: ")

print("")
print("--------------------")
print("Tu historia Mad Libs")
print("********************")
print("")

print("Antes del Coronavirus, me levantaba a las " + time_a + ".")
print("Me bañaba, cepillaba mi/s " + body_part + " y comía " + food + " de desayuno.")
print("Iba a la " + educative_centre + " a las 8:30 a.m.")
print("Mi materia preferida es " + lesson_01 + ", pero no me gusta " + lesson_02 + ".")
print("Después de la " + educative_centre + ", " + hobby + " y me iba a dormir a las " + time_b + ".")
print("Ahora, " + mourning_task + " a las 9 a.m. Tengo clases virtuales en mi " + electric_device + ".")
print("Me gustan las clases virtuales, pero a veces son " + adjetive + ".")
print("Tengo mucho tiempo libre y a veces " + home_task + ",")
print("pero no puedo salir y " + outside_task + ".")
print("De vez en cuando hago video llamadas con mi mejor amigo, " + name + ".")
print("No me molesta quedarme en casa,")
print("pero quiero que termine la cuarentena en " + month + ".")
